package dev.shorthouse.remindme.utilities

const val DAYS_IN_YEAR = 365
const val HOURS_IN_DAY = 24
const val DAYS_IN_WEEK = 7
const val ONE_INTERVAL = 1

const val KEY_REMINDER_NAME = "KEY_REMINDER_NAME"
const val REMINDER_NOTIFICATION_ID = 1
const val NOTIFICATION_UNIQUE_WORK_NAME_PREFIX = "NOTIFICATION_UNIQUE_WORK_NAME_PREFIX"

const val RESCHEDULE_ALARMS_SERVICE_CHANNEL_ID = "RESCHEDULE_ALARMS_SERVICE_CHANNEL_ID"
const val RESCHEDULE_ALARMS_SERVICE_ID = 1

const val UPDATE_REMINDER_TIME_ZONE__SERVICE_CHANNEL_ID = "UPDATE_REMINDER_TIME_ZONE__SERVICE_CHANNEL_ID"
const val UPDATE_REMINDER_TIME_ZONE_SERVICE_ID = 2

const val UPDATED_TIME_ZONE_EXTRA = "time-zone"
const val DATE_PATTERN = "dd MMM yyyy"